### ISSUE TITLE
Bootstrap is not working properly

### ISSUE THREAD

**Issue by pulsarav** [mirumee/saleor#1761] opened 2018-02-07 15:58 UTC
Hello guys, I've been trying to use Bootstrap modals and other utils, but it seems is not fully working, including your demo on https://demo.getsaleor.com/ the mobile version (iPhone 5s safari) will not get the menu and the search bar is always on top, I found it because is I tried to add a couple modals and a carrousel, but is like the bootstrap js file was not loading at all. 

I've added bootstrap completely or partials to the storefront.js but didn't work.
import 'bootstrap';
import 'bootstrap/js/dist/util';
import 'bootstrap/js/dist/dropdown';

 I'm a newbie on webpack so I tried to follow a couple tutorials online but neither work.

I'm assuming is has something to do with this issue https://github.com/shakacode/bootstrap-loader/issues/172

**Comment by Pacu2** [comment] 2018-02-07 16:02
Hi @pulsarav,
Could you please provide screenshots of the issue? It will be easier to investigate.

**Comment by pulsarav** [comment] 2018-02-07 16:33
ios 10.3.3
![whatsapp image 2018-02-07 at 11 24 21 am](https://user-images.githubusercontent.com/6465803/35927815-a3d8b958-0bf9-11e8-9dc8-023d0904e6ac.jpeg)

**Comment by NyanKiyoshi** [comment] 2018-02-28 14:48
Hiya! 

One of of the person I'm working with has this issue with his iPhone 6 on our post-production website, which is the January release. Firefox focus on the iPhone 6, which I would guess use the Safari Webkit from the iPhone, also have the issue (which I don't have on Firefox Focus Android, which runs on the Chromium Webkit).

I'm gonna try to debug that during this week. At least I'm gonna try to find a way to do so. If someone can or could help me with that, that would really be great since I know nothing about Apple, and even more about iPhones. I also can have access to a Macbook if I need to debug it.

We must find a way to fix this bug, if it happened to us, it will happen to other Saleor user in production.

**Comment by patrys** [comment] 2018-02-28 14:54
Can we reproduce this on BrowserStack?

**Comment by NyanKiyoshi** [comment] 2018-02-28 15:02
I took a look, they have the iPhone 6. I will look further into that and I will keep you updated. I also know that Mozilla is a partner of another service just like that, I think it's also free for open-source, so if it doesn't work there, there is always this one as well. But I don't remember the name and can't find it right now, I need to do more searches.

Also, his phone was not his, the other iPhone did work without running into any issue and he just told me it was an iPhone 6. So... I would guess this is an issue with a specific version range of the Safari Webkit... Will see.

**Comment by patrys** [comment] 2018-02-28 15:18
If it can be reproduced on BrowserStack then it should be easily fixable as I believe Mirumee has as professional account with them.

**Comment by NyanKiyoshi** [comment] 2018-02-28 15:20
Here we go.

![](https://i.imgur.com/YTuP7I2.png)

I have no clue how saleor is working into that, I will try to look but I not sure if I can find something. My trial period is gonna expire soon but I did request a open-source access (which I could share to anyone if they accept it soon).

**Comment by NyanKiyoshi** [comment] 2018-02-28 16:59
@patrys it should fix this issue. It did fix the issue on browserstack.com. It doesn't seem to break anything (I had a hard time for that, because it was a easy fix but broke everything for other browsers than safari...). 

It was the width: 100% and width: 100vw. It's a bug from Safari.

```diff
@@ -115,6 +120,7 @@
     @include media-breakpoint-down(sm) {
       position: fixed;
       top: 0;
+      left: 0;
       width: 100vw;
       background-color: $white;
       z-index: 4;
```

I found that https://github.com/Hiswe/vh-check. So, what seemed to be happening is that the search bar that should be hidden by the header thanks to the `position: static` and the `width: 100vw` was pushing away the header. 

So `left: 0` fixed it. The other way was removing the `width: 100vm` and the `width: 100%` using `width: auto` or `width: inherit`. It was working on Safari, Safari was making the header take the whole viewport but not the other browsers, breaking everything.

----

I also di some changes:

```diff
@@ -35,6 +35,9 @@
 .navbar {
   padding: 0;
   @include media-breakpoint-down(sm) {
+    > .container-fluid {
+      padding: 0;
+    }
     svg {
       max-height: 30px;
       width: auto;
```

This one is to make the visual better, less compact.
- [before](https://i.imgur.com/O5cfLGm.png)
- [after](https://i.imgur.com/bxOFqaz.png)


-----

```diff
   &__logo {
     padding: $global-padding * 2 0;
+    display: flex;
+    align-items: center;
     .menu-icon-mobile {
       position: relative;
       display: inline-block;
```

This addition is to avoid that: https://i.imgur.com/Hx9kDyG.png

**Comment by NyanKiyoshi** [comment] 2018-03-01 13:32
Note: I will open a PR soon with those changes, but not to merge right now. I want to do more checks but I have issues with the emulation since it's a trial software... So I will do IRL tests probably on this Saturday.

There are a few things bugging me out, I think those are Safari bugs that were already there though.

Like, you can see the "menu" text not being correctly centered. This issue seems to be on Safari but I don't have it on my desktop and not on my mobile.

There is also the sidebar that is being overlapped by the filters header on mobile.

![](https://i.imgur.com/pu4SlgK.png)

Which was easily fixed in our post-production (it was reported to me because one of the categories wasn't visible because of that overlapped navbar. Not sure if it's a Safari bug making Safari not take into account the `top: {xx}px` that you set).

![](https://i.imgur.com/IDSviv0.png)

**Our fix:**
![](https://i.imgur.com/wWQckpZ.png)

-----

Also, this bug is not on saleor's master, simply because this is totally gone. I'm pretty sure it's a bug. See below: no possibility to open filters.

![](https://i.imgur.com/wLAovsK.png)

**Closed** 2018-03-12 09:42 UTC
