### ISSUE TITLE
navbar menu is not refreshed when menu item is deleted

### ISSUE THREAD

**Issue by tiberiuichim** [mirumee/saleor#3547] opened 2019-01-04 15:05 UTC
When editing a menu item it recalculates the json_content field for the menu. This doesn't happen when a menu item is removed from the menu.

**Comment by jakubwi** [comment] 2019-01-30 14:38
I was trying to reproduce this, but couldn't. 
https://github.com/mirumee/saleor/blob/a6fe9dcb455816846e18bbe8d5b18ac1c657688e/saleor/dashboard/menu/views.py#L161
https://github.com/mirumee/saleor/blob/a6fe9dcb455816846e18bbe8d5b18ac1c657688e/saleor/dashboard/menu/utils.py#L73
It looks like the menu_item_delete view updates 'json_content' field. 

Are you using the newest version of Saleor? If so, could you provide any steps to reproduce this bug?

**Comment by Pacu2** [comment] 2019-01-30 15:13
Thanks @jakubwi , seems like a bug is not present on the latest version of Saleor.

Closing for now, please reopen if the bug exists on the latest version.

**Closed by Pacu2** 2019-01-30 15:13 UTC
Labels: bug
