### ISSUE TITLE
404 page issue

### ISSUE THREAD

**Issue by ajaypratapyadav** [mirumee/saleor#2675] opened 2018-08-24 11:01 UTC
### What I'm trying to achieve
…
I want 404 page when page not found
### Steps to reproduce the problem
1. when i make debug=False give Server Error 500
2. when i enter wrong url give default django error

### What I expected to happen
… i want same functionality like https://demo.getsaleor.com/en/ return on page not found

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by NyanKiyoshi** [comment] 2018-08-24 11:51
I cannot reproduce it. Could you give us some more details and the error stack trace?

**Comment by Pacu2** [comment] 2018-08-25 10:32
Static files are served by Django only in DEBUG mode, for production use is recommended to serve them from the external resource, eg. Amazon S3 buckets. We have integration guide for it somewhere in the docs

**Comment by Pacu2** [comment] 2018-10-01 17:05
Closing for now, please reopen if you have further questions.

**Closed by Pacu2** 2018-10-01 17:05 UTC
