### ISSUE TITLE
Ship only orders that require it

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2935] opened 2018-09-21 10:40 UTC
### What I'm trying to achieve
To ship order that requires no shipping (because there are no products that require shipping).

### Steps to reproduce the problem
1. Create draft order
2. Add a product that requires no shipping
3. Shipping method choice is available

### What I expected to happen
Shipping method choice should be unavailable.

**Comment by Pacu2** [comment] 2018-09-21 10:45
This is already handled by the Dashboard 2.0

**Comment by ajostergaard** [comment] 2018-10-07 18:38
@Pacu2 if already handled why "help wanted" and "hacktoberfest"? :-S

**Comment by ajostergaard** [comment] 2018-10-07 18:42
Also, not duplicate of #2934? Or is it one for shop and one for dashboard? Sorry but not clear from tickets.

**Comment by Pacu2** [comment] 2018-10-07 18:48
@ajostergaard We are developing the new dashboard called Dashboard 2.0 at this moment (it's pre-beta), you can check out the dashboard 2.0 at `/dashboard/next/`
The ticket you've linked, #2934, threats the ReactJS part of the functionality on the new dashboard.

The bug mentioned in this ticket is present in the regular dashboard. (available at `/dashboard/`)

**Comment by ajostergaard** [comment] 2018-10-07 18:57
Ok - thanks. I'll pick this up and resolved in current dashboard in the next couple of days.

**Comment by Pacu2** [comment] 2018-10-07 19:05
Glad to hear that, I took the labels off, for now

**Comment by Pacu2** [comment] 2018-10-12 17:31
I think that the issue persits if you create an draft order from the dashboard, with products that do not require shipping. 

Could yo please follow the steps to reproduce that are listed in the main post?

**Comment by ajostergaard** [comment] 2018-10-12 17:33
I'm an idiot - I completely forgot it was the dashboard... brb while I go bang my head against a door. ;)

**Comment by Pacu2** [comment] 2018-10-12 17:35
@ajostergaard No worries, happened to all of us at some point :)

**Comment by ajostergaard** [comment] 2018-10-12 18:53
Do we want shipping to be hidden until products which require shipping are added to the draft order or do we just want shipping visible but not editable? I prefer the latter so will do that but happy to pivot if mirumee prefer the former.

**Closed** 2019-03-11 13:53 UTC
Labels: bug, dashboard 1.0, in progress
