### ISSUE TITLE
Horizontal scroll bar on landing page

### ISSUE THREAD

**Issue by Ildarik** [mirumee/saleor#5708] opened 2020-05-27 11:56 UTC
There is an awkward horizontal scroll bar on your landing page: https://saleor.io/

See on the screenshot at the bottom. My screen resolution is 1366x768

![Screenshot from 2020-05-27 14-54-24](https://user-images.githubusercontent.com/10713674/83016026-028bac00-a02a-11ea-8b32-6dbded8d56e2.png)

**Comment by NyanKiyoshi** [comment] 2020-05-27 12:06
Transferred the issue to the proper team.

Managed to reproduce on Firefox 78.0a1. Looks like the responsive scaling is kicking in a too small dimension than it actually should.

**Comment by NyanKiyoshi** [comment] 2020-07-08 15:34
Hi! It is now fixed for Chrome and Firefox, but still an issue on Safari. Thanks for the report!

**Closed by NyanKiyoshi** 2020-07-08 15:34 UTC
Labels: bug
