### ISSUE TITLE
Do we need alias in the address book model

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#238] opened 2014-12-18 09:10 UTC
Yesterday we had conversation about aliases in address book models, we came up with conclution that address is pretty unique value and it doesn't need any aliases.

Why we used them in first place? Any one remember @patrys, @artursmet, @bogdal ?

**Comment by patrys** [comment] 2015-05-05 10:19
Dupe of #201

**Closed** 2015-05-05 10:19 UTC
Labels: duplicate, enhancement
