### ISSUE TITLE
Dashboard 2.0: edit customer view

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2870] opened 2018-09-14 16:48 UTC
### What I'm trying to achieve
To reassign order to another customer.

### Steps to reproduce the problem
1. Enter order details of an order
2. Click on an edit 
3. Select customer
4. Click submit

### What I expected to happen
To reassign order to the selected customer.

**Comment by patrys** [comment] 2018-09-14 16:59
Duplicate of #2863

**Closed by patrys** 2018-09-14 16:59 UTC
Labels: bug, react
