### ISSUE TITLE
GraphQLLocatedError: 'str' object has no attribute 'items' In Dashboard V2

### ISSUE THREAD

**Issue by monoxane** [mirumee/saleor#3882] opened 2019-03-29 05:32 UTC
### What I'm trying to achieve
Add Products

### Steps to reproduce the problem
_using new dashboard_
1. follow https://docs.getsaleor.com/en/latest/customization/docker.html
2. add product type
3. add product like so:
![image](https://user-images.githubusercontent.com/16844830/55211421-02362c00-5240-11e9-90a6-f207a21ddfd7.png)
4. save product
5. click on product to edit it
6. ???
7. error

### What I expected to happen
Product to be added and functional

### Screenshot of error
![image](https://user-images.githubusercontent.com/16844830/55211359-bc796380-523f-11e9-929b-fc0f7cd337e3.png)

**System information**
Docker Version | 18.09.0
API version | 1.39
Go version | go1.10.4
OS type | linux
OS | Debian GNU/Linux 9 (stretch)
Architecture | amd64
Kernel version | 4.9.0-8-amd64

Browser: Chrome Version 69.0.3497.100 (Official Build) built on Debian stretch/9.5, running on Debian stretch/9.8 (64-bit)

**Comment by monoxane** [comment] 2019-03-29 05:39
looks like it only occurs on products that also cause  #3873

**Comment by monoxane** [comment] 2019-03-29 05:41
Restarting the docker-compose stack fixes it 2 out of 3 times (random chance), fixes it for all instances of that error, error does not occur again until the stack is restarted again, then theres another 1 third chance of the error occuring on any product

**Comment by maarcingebala** [comment] 2019-03-29 11:52
I think it's a duplicate of #3873.

**Closed by maarcingebala** 2019-03-29 11:52 UTC
Labels: bug
