### ISSUE TITLE
TokenRefresh mutation also gives "Signature has expired" error

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#5650] opened 2020-05-14 15:10 UTC
### What I'm trying to achieve
When `JWT_VERIFY_EXPIRATION=True`, if the token expires, any attempts to refresh the token also result in the same "Signature has expired" error. Using the new 2.10 release.

### Steps to reproduce the problem
1. Set `JWT_VERIFY_EXPIRATION=True`
2. Attempt to refresh an expired token

### What I expected to happen
The token should be refreshed.

**System information**
Operating system: Windows 10 x64

**Comment by maarcingebala** [comment] 2020-05-25 10:13
This is related to the issue https://github.com/mirumee/saleor/issues/5128. We'll be soon working on a refactoring of JWT mutations in Saleor to fix this.

**Comment by WahabShah23** [comment] 2020-06-23 16:14
Hello, so I am getting this error, "Signature verification failed". Token is being generated perfectly but the problem is when I pass that token to headers as required for relevant apis I m getting this error of signature verification failed. Can you kindly tell what could be the issue? Its happening in my app as well as on playground (even the new token that is received from tokenCreate mutation, it throws the same error)

**Comment by korycins** [comment] 2020-06-30 09:47
New JWT auth layer rebuilt in #5734 should solve the problem. I am closing the issue for now.

**Closed by korycins** 2020-06-30 09:47 UTC
Labels: bug
