### ISSUE TITLE
graphql_jwt.exceptions.PermissionDenied: You do not have permission to perform this action

### ISSUE THREAD

**Issue by ehsanbarkhordar** [mirumee/saleor#5113] opened 2019-12-25 13:03 UTC
### I want to deploy full saleor store(saleor/saleor-dashboard/saleor-storefront) with docker but i catught and expection that means have no permissn to query in graphql api and storefront cant load the main site.
…

### Steps to reproduce the problem
1. git clone https://github.com/mirumee/saleor.git
2. cd saleor
3. docker-compose build
4. And continue to see in accordance with the documentation
![Screenshot from 2019-12-25 16-32-56](https://user-images.githubusercontent.com/22658149/71446013-405f6e00-2734-11ea-8e1c-04d57c7df0ab.png)

### What I expected to happen
load normally the site like before.

### Screenshots
![Screenshot from 2019-12-25 16-28-55](https://user-images.githubusercontent.com/22658149/71445965-dd6dd700-2733-11ea-9fc0-c9e76c8f3595.png)

**System information**
Operating system:
ubuntu 18:04

**Comment by karolkielecki** [comment] 2019-12-27 15:36
@ehsanbarkhordar Hi there! Due to the holiday season, our support is limited. We'll try to help you as soon as we can. Thanks for understanding.

**Comment by karolkielecki** [comment] 2019-12-30 13:14
@ehsanbarkhordar Hey! Did you prepare the database? https://docs.saleor.io/docs/getting-started/docker/#how-to-use-docker

**Comment by karolkielecki** [comment] 2019-12-30 15:23
@ehsanbarkhordar Hey! Did you prepare the database? https://docs.saleor.io/docs/getting-started/docker/#how-to-use-docker

**Comment by thewjones** [comment] 2020-01-02 23:02
I had this issue too. Opening a private browsing window or clearing cookies resolved it for me. So I think it's something to do with failed JWT credentials from previous sessions getting stored and not expiring?

**Comment by tboulogne** [comment] 2020-01-05 15:04
Hello,

Any idea how to fix this please ? 
@thewjones your tips works sometimes not all... :-(

Thanks for help.

Regards

**Comment by closelookadmin** [comment] 2020-01-18 13:11
I have the same issue

**Comment by karolkielecki** [comment] 2020-01-20 12:35
@tboulogne @closelookadmin Could you please tell me all the steps you have taken? We need more details. It will help us to reproduce the issue.

**Comment by devyog** [comment] 2020-01-22 05:51
facing the same issue when adding attributes to any particular product. Although as mentioned by @thewjones the issue can be resolved by opening private window. But this should not happen as there is no way users of the store going to open the store in private window :)

**Comment by karolkielecki** [comment] 2020-01-28 11:59
@devyog It might be related to apollo cache. We need to know all the steps you have taken, and we'll try to reproduce it.

**Closed** 2020-02-07 12:06 UTC

**Comment by ehutzle** [comment] 2020-07-10 15:04
> I had this issue too. Opening a private browsing window or clearing cookies resolved it for me. So I think it's something to do with failed JWT credentials from previous sessions getting stored and not expiring?

Well - I know this is merged, but this is an issue that I am still dealing with. Not sure about GitHub ettiequte, sorry if this isn't typical.
