### ISSUE TITLE
Can't load the graphql SCHEMA

### ISSUE THREAD

**Issue by raviitsoft** [mirumee/saleor#5846] opened 2020-07-03 13:03 UTC
### Steps to reproduce the problem
1.  open the URL: https://pwa.demo.saleor.rocks/graphql/
2. Click on Schema tab and white screen load

### Screenshots

<img width="1764" alt="2020-07-03_18-32-07" src="https://user-images.githubusercontent.com/3480373/86471806-acfa9b80-bd5b-11ea-9ea4-d56773958d85.png">

**System information**
Operating system:

**Comment by patrys** [comment] 2020-07-03 13:24
Duplicate of #5719

**Closed by patrys** 2020-07-03 13:24 UTC
