### ISSUE TITLE
Dashboard next: Navigation allows to link anything, breaks on edition

### ISSUE THREAD

**Issue by LeBenLeBen** [mirumee/saleor#4230] opened 2019-06-06 09:10 UTC
### What I'm trying to achieve
I'm trying to add links in my navigation.

### Steps to reproduce the problem
1. In the dashboard next, go to the navigation management and create a new item.
2. In the link field, enter whatever you want, for example "#" (skip the wizard to select a collection/category/page).
3. The link item is created properly
4. Edit the link
👉 The page gets blank and the console show an error: `Error: Unknown type`

### What I expected to happen
Either being able to edit any link value or not being able to save a navigation item with string as  link value on creation.

**System information**
Operating system: MacOS 10.14.5
Browser: Firefox 67.0.1

**Comment by maarcingebala** [comment] 2019-06-11 07:16
@dominik-zeglen Is this a known error?

**Comment by dominik-zeglen** [comment] 2019-06-11 09:28
Now it is

**Comment by maarcingebala** [comment] 2019-08-08 10:15
@LeBenLeBen Hey, could you check if this error still occurs? I'm testing it on current master and cannot reproduce it. Basically, if I type some random characters in the link field, it doesn't get saved at all. When editing it later the field is empty.

**Comment by maarcingebala** [comment] 2019-08-12 07:32
I think the issue is fixed by now, please reopen if it still occurs.

**Closed by maarcingebala** 2019-08-12 07:32 UTC
Labels: bug, dashboard 2.0
