### ISSUE TITLE
Safari browser - drag and drop photo doesn't work.

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1511] opened 2017-12-20 12:56 UTC
On OSX Safari browser - Version 11.0.2 (13604.4.7.1.3), product photos drag and drop functions does not work.

**Comment by dominik-zeglen** [comment] 2017-12-21 13:29
Hello @maltitco !
Unfortunately, this is caused by NPM package `dropzone`, and we can do nothing about it. Please remember that you can add images by clicking 'drop here (...)' text or circular blue button at the top of the page.

**Comment by dotslash227** [comment] 2018-01-01 06:39
This happens on Manjaro Linux as well.

**Comment by dominik-zeglen** [comment] 2018-01-02 10:37
At this moment we are waiting for this issue https://github.com/enyo/dropzone/issues/1640 to be resolved.

**Comment by maltitco** [comment] 2018-01-03 08:30
@dominik-zeglen I checked the demo on the dropzone page and everything works fine there, so it can be a problem with the implementation.

**Comment by elwoodxblues** [comment] 2018-02-20 08:35
@dominik-zeglen It seems that there is a new Dropzone version that fixes this issue: https://github.com/enyo/dropzone/issues/1640#issuecomment-365888390

**Comment by tomcio1205** [comment] 2018-10-08 14:15
@dominik-zeglen, @Pacu2 I tested it right now and with Safari 12.0 it working well, so I don't know if this problem still exists

**Comment by NyanKiyoshi** [comment] 2019-09-27 13:11
Should have been fixed in `dropzone` 5.3.0 (5.5.1 is currently used).

**Closed by NyanKiyoshi** 2019-09-27 13:11 UTC
Labels: bug, help wanted
