### ISSUE TITLE
Demo Plugin

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#4858] opened 2019-10-16 12:48 UTC
Deploy of demo saleor on `https://demo.getsaleor.com/en/` requires a lot of manual work, to turn on `Read-Only` mode. We could write a plugin to block all admin's mutations and enable it for demo server.

**Comment by maarcingebala** [comment] 2019-10-16 12:50
Duplicate of: https://github.com/mirumee/saleor/issues/4853

**Closed by maarcingebala** 2019-10-16 12:50 UTC
