### ISSUE TITLE
Dashboard sections require superuser permission

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1271] opened 2017-11-08 08:27 UTC
To access some of the features (attributes, product class, sites, groups, staff) in the Dashboard, one need to have a superuser status. 

It would be more convenient to create new permissions for those sections.

**Comment by koradon** [comment] 2017-11-08 08:32
For groups and staff we already work on it in #1267

**Comment by elwoodxblues** [comment] 2017-11-08 08:38
Duplicate of #1259

**Closed by elwoodxblues** 2017-11-08 08:38 UTC
Labels: dashboard
