### ISSUE TITLE
WebpackError at / 

### ISSUE THREAD

**Issue by sagoyanfisic** [mirumee/saleor#657] opened 2016-12-13 17:38 UTC
I have a problem starting Saleor, it generates an error

Internal Server Error: /
Traceback (most recent call last):
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 40, in render_bundle
    return render_as_tags(_get_bundle(bundle_name, extension, config), attrs)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 32, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/webpack_loader/loader.py", line 94, in get_bundle
    raise WebpackError(error)
WebpackError: 
            ModuleBuildError in 
            Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss-loader/index.js:93:10)
            
[13/Dec/2016 11:34:50] "GET / HTTP/1.1" 500 142037
Internal Server Error: /
Traceback (most recent call last):
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 40, in render_bundle
    return render_as_tags(_get_bundle(bundle_name, extension, config), attrs)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 32, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/home/msalinas/Documentos/e-commerce/env_saleor/local/lib/python2.7/site-packages/webpack_loader/loader.py", line 94, in get_bundle
    raise WebpackError(error)
WebpackError: 
            ModuleBuildError in 
            Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss-loader/index.js:93:10)
            
[13/Dec/2016 11:34:51] "GET / HTTP/1.1" 500 142037

**Comment by patrys** [comment] 2016-12-13 17:39
This is duplicate of #656

**Closed by patrys** 2016-12-13 17:39 UTC
Labels: duplicate
