### ISSUE TITLE
Dashboard breadcrumbs padding issue

### ISSUE THREAD

**Issue by koradon** [mirumee/saleor#1418] opened 2017-12-05 11:58 UTC
Breadcrumbs on some page zoom values renders with wrong padding.
It occurs with zoom 80%, 110%

### What I'm trying to achieve

Breadcrumbs should have same padding on every zoom.

### Steps to reproduce the problem

1. Set page zoom on 110% or 80%
2. Go to dashboard

### What I expected to happen

Breadcrumbs should have same padding on every zoom.

### What happened instead/how it failed

Breadcrumbs have big left padding.

![screenshot from 2017-12-05 12-53-27](https://user-images.githubusercontent.com/11785371/33605941-fd53eb4e-d9bb-11e7-905d-8a1a9954a760.png)

**Comment by dominik-zeglen** [comment] 2017-12-20 10:36
Can anyone reproduce this bug? It does not show up on MacOS High Sierra / Chrome 63.

**Comment by Pacu2** [comment] 2018-10-03 06:38
I think this is resolved by now Cannot reproduce either

**Closed by Pacu2** 2018-10-03 06:38 UTC
Labels: bug, dashboard, frontend
