### ISSUE TITLE
Server Error (500) when adding attribute

### ISSUE THREAD

**Issue by kaustubhrpatil** [mirumee/saleor#895] opened 2017-02-08 13:22 UTC
Hi,

First of all thanks for this excellent software, makes my life easier.

I deployed it on heroku using the heroku elements (https://elements.heroku.com/buttons/mirumee/saleor).

Then I tried to add an attribute but that resulted in Server Error (500) page. Is this expected behavior? Any settings that have to be changed? If yes then any way to do that on heroku?

Thanks!

**Comment by patrys** [comment] 2017-02-10 13:47
This was caused by a bug in the backend code. Fixed now, thank you for reporting.

**Closed** 2017-02-10 13:46 UTC
Labels: bug, in progress

**Comment by kaustubhrpatil** [comment] 2017-02-13 11:35
Thanks a lot.

Is this also fixed on the heroku element?
