### ISSUE TITLE
Will Saleor support MySQL?

### ISSUE THREAD

**Issue by imakin** [mirumee/saleor#368] opened 2015-10-14 14:06 UTC
hello, wanna know if saleor support MySQL. I've tested this on MySQL database but it needs some work around:

db_index in saleor.registrations.models.ExternalUserData should be changed to CharField with defined max_length
```
    service = models.CharField(db_index=True, max_length=255)
    username = models.CharField(db_index=True, max_length=255)
```

in saleor.dashboard.product.forms.StockBulkDeleteForm there is mysql problem when it was called. (Delete action in product stock). The MySQL problem is similar to what was described here http://stackoverflow.com/questions/45494/mysql-error-1093-cant-specify-target-table-for-update-in-from-clause

Can be corrected this way
```
class StockBulkDeleteForm(forms.Form):
    items = forms.ModelMultipleChoiceField(queryset=Stock.objects)

    def delete(self):
        items = Stock.objects.filter(pk__in=self.cleaned_data['items'])
        for item in items:
                item.delete()
```
i've tested the Bulkvariant delete though, no error without changing anything, still okay with `items.delete()` for bulkvariantdelete

**Comment by patrys** [comment] 2015-10-14 14:08
In theory we should support all database backends Django supports right now. Is there anything not working in MySQL?

**Comment by imakin** [comment] 2015-10-14 14:16
sorry missclicked submit button before finished typing

this is the error occured in 2nd problem
![slerr](https://cloud.githubusercontent.com/assets/6647566/10486303/926a55c8-72b8-11e5-8d44-046eb22cde03.jpg)
mysql 5.6.21

**Comment by mitcom** [comment] 2015-12-04 16:49
Hi @imakin, in PR #422 I changed these fields in registration model.
But I cannot reproduce the second issue. I tested with Django 1.8.4 and 1.8.7. Can you check with the newest Saleor and provide more information. How many stock entries did you try to delete?  If there were all of product stocks.

**Comment by patrys** [comment] 2015-12-07 11:39
I'll close this and assume it's fixed since we can't reproduce the second part of the problem.

**Closed by patrys** 2015-12-07 11:39 UTC
Labels: bug

**Comment by prashante114** [comment] 2017-01-23 10:59
Hi All, 

I am new to django and saleor and  I got same error while migrating db to MySql. ""BLOB/TEXT column 'service' used in key specification without a key length""

I referred above links and searched for the solution. But I didn't get any specific solution to solve this error. Could someone please help me what should I do to resolve this error.

**Comment by prashante114** [comment] 2017-01-23 11:01
Hope to get solution soon.

**Comment by artursmet** [comment] 2017-01-23 11:05
Hi @prashante114,

Some time ago we've decided to require PotgreSQL as a database backend (https://github.com/mirumee/saleor/issues/633). We're usiing some Postgres-specific field types like JSONField. So everything should work for you if you swirch from MySQL to PostgreSQL.
Saleor delivers docker-compose config, so it should be easy to setup required services without need to install anything manually.

**Comment by patrys** [comment] 2017-01-23 11:41
To add to that, we currently have no plans to officially support other database engines but if you absolutely need to use MySQL it should be possible to manually remove parts of Saleor that depend on PostgreSQL (for example search currently depends on hstore column type that is specific to Postgres).
