### ISSUE TITLE
fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed.

### ISSUE THREAD

**Issue by Megidd** [mirumee/saleor#7279] opened 2021-05-03 14:37 UTC
Git cloning the repo on a Windows 10 machine throws this error:

> error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.

```
>git clone https://github.com/mirumee/saleor.git
Cloning into 'saleor'...
remote: Enumerating objects: 187180, done.
remote: Counting objects: 100% (289/289), done.
remote: Compressing objects: 100% (225/225), done.
remote: Total 187180 (delta 136), reused 131 (delta 64), pack-reused 186891
Receiving objects: 100% (187180/187180), 105.28 MiB | 234.00 KiB/s, done.
Resolving deltas: 100% (137187/137187), done.
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```

**Comment by Megidd** [comment] 2021-05-03 14:52
It might be due to colons in the filename:

https://stackoverflow.com/a/61187913/3405291

Or the file path is too large:

https://stackoverflow.com/a/55229104/3405291

**Comment by krzysztofwolski** [comment] 2021-05-05 17:57
Duplicate of #7135. Closing.

**Closed by krzysztofwolski** 2021-05-05 17:57 UTC
Labels: bug
