### ISSUE TITLE
Dashboard voucher form fails validation

### ISSUE THREAD

**Issue by royal-mcb** [mirumee/saleor#572] opened 2016-10-11 22:22 UTC
In **Chrome** 

- Attempt to add a voucher that is not a Category or Product voucher.
- Browser-side validation fails on hidden category and product fields.
- To user, failure is invisible and silent - just appears to do nothing.

ProductVoucherForm and CategoryVoucherForm's init methods explicitly set those fields as required. Setting required to false removes this issue, but has the side effect of allowing product or category vouchers to be created without specifying a product or category.

**Comment by artursmet** [comment] 2016-10-12 06:55
@royal-mcb Could you check if the issue still occurs with latest code from master branch?
I can't recreate it - when I try to create a voucher for all products, everything works fine:

![image](https://cloud.githubusercontent.com/assets/1754812/19300250/96ba85d4-9059-11e6-9548-fe2b001fa431.png)

**Comment by royal-mcb** [comment] 2016-10-12 17:49
Cloned a new copy of the master branch, set up a new virtualenv and pip installed requirements.txt. I'm running on Ubuntu 14.04 with python2.7 and Django 1.10.1

In Chrome 53.0.2785.143, clicking the update button has no effect, and I get this error in dev console:
![chrome](https://cloud.githubusercontent.com/assets/22780200/19321090/e55350d6-9068-11e6-8dee-03c5398972c8.png)
In Firefox 49.0.1 I get no errors in the console, but instead get the validation failure notice posted at the top left.
![firefox](https://cloud.githubusercontent.com/assets/22780200/19321232/0aececda-9069-11e6-8de2-6787ddf85a2a.png)

If I manually toggle all the voucher types one by one, and select a product and a category, the form then allows me to create whatever voucher type I want- because now the client sees that the 'required' fields have data in them, even if the backend ignores that data.

**Comment by patrys** [comment] 2016-10-12 22:17
This looks like a bug in how controls are rendered in HTML. We should not depend on client side validation (or the `required` attribute).

**Comment by royal-mcb** [comment] 2016-10-12 23:07
I agree that client side validation shouldn't be depended upon, but I think it does make a nice preliminary check. Being fully client-side prevents a hit against the server, and, when it works, feels very responsive as a user.

The issue is that whatever javascript code which handles hiding the unused form elements doesn't add or remove the 'required' attribute programmatically-- and then browsers freak out about hidden required forms-- or worse, fail silently. 

To be future-proof you'd want to, say, select all fields with the required attribute as they're being hidden, remove the attribute and mark them with a dummy css tag or something so that you know what they were, and then when you unhide them simply replace the dummy tag with the actual attribute.

**Comment by patrys** [comment] 2016-10-13 06:18
You are right but there is currently no such code in place so triggering client side form validation is a bug.

**Comment by artursmet** [comment] 2016-10-13 08:13
@royal-mcb Now I managed to reproduce it, probably I was checking older version of the branch. This issue will be fixed soon.

**Closed** 2016-10-17 07:49 UTC
Labels: bug, frontend
