### ISSUE TITLE
Saleor and Wagtail integration throws exception when trying to view wagtail pages.

### ISSUE THREAD

**Issue by Premitium** [mirumee/saleor#1425] opened 2017-12-05 16:24 UTC
I have a clean install of Saleor and integrated Wagtail with it.

When I try to see a wagtail page I get an exception at the wagtail end at:

.virtualenvs/srt/lib/python3.6/site-packages/wagtail/wagtailcore/views.py in serve, line 19

Cannot query "localhost:8000": Must be "Site" instance.

Also if I want to access the page from the front with a url I get:

AttributeError at /pages/
'Site' object has no attribute 'root_page'

I am asking since I saw that you are using Wagtail from a twitter [post](https://twitter.com/getsaleor/status/607858512463433728?lang=en). 
Hope you have a solution for that.

Also if you have a working recipe of how to implement Saleor and Wagtail together It would be appreciated!

**Comment by patrys** [comment] 2017-12-05 16:53
It's been some time since we used these two together. It looks like there is a conflict now between `wagtail.core.middleware.SiteMiddleware` and `saleor.core.middleware.ClearSiteCacheMiddleware`. You could try moving the Saleor middleware one above the Wagtail one but I'm not sure if that will fix it or if that's the only incompatibility today.

**Comment by Premitium** [comment] 2017-12-05 17:04
Thank you I will try it out.Do you recommend another CMS that works out of the box with saleor?


Sent from Yahoo Mail for iPhone


On Tuesday, December 5, 2017, 18:53, Patryk Zawadzki <notifications@github.com> wrote:


It's been some time since we used these two together. It looks like there is a conflict now between wagtail.core.middleware.SiteMiddleware and saleor.core.middleware.ClearSiteCacheMiddleware. You could try moving the Saleor middleware one above the Wagtail one but I'm not sure if that will fix it or if that's the only incompatibility today.

**Comment by patrys** [comment] 2017-12-05 17:07
Sadly, no, if I required a full-fledged CMS (our customers are usually find with just a WYSIWYG editor + `django.contrib.flatpages`), Wagtail would likely be my first choice.

**Comment by patrys** [comment] 2017-12-05 17:13
I'll keep this open as I'm interested to see what other challenges you face while trying to use Saleor with Wagtail. Hopefully we can adapt to make it easier, document the necessary adaptations or even have it working our of the box.

**Comment by Premitium** [comment] 2017-12-06 11:20
Changing the order of the middleware classes did the trick. It all seems to work fine no. If something comes up I will post.

**Comment by fpytloun** [comment] 2018-08-20 13:41
Hello,
I tried to integrate Wagtail with Saleor and it works but I can't see Add page option in Pages which is weird. Anyone facing the same issue? Permissions seem to be ok for admin user, maybe it's Wagtail bug?

**Comment by auvipy** [comment] 2019-04-11 16:43
I am going to try to convert saleor models to wagtail page and editable through admin and rendered using wagtail django templates. if i can do so, i will open source that

**Comment by maarcingebala** [comment] 2019-07-09 11:46
Closing this since we're not going to work on any integration with Wagtail for now.

**Closed by maarcingebala** 2019-07-09 11:46 UTC

**Comment by jobbbk** [comment] 2019-11-21 07:58
> I am going to try to convert saleor models to wagtail page and editable through admin and rendered using wagtail django templates. if i can do so, i will open source that

any progress on this? am still stuck in the wagtail.core.middleware.SiteMiddleware and saleor.core.middleware.ClearSiteCacheMiddleware conflict. Any help will be appreciated

**Comment by AguD** [comment] 2019-12-20 11:02
The problem is that Saleor uses Django.contrib.sites Site model (1to1 link with saleor.site.SiteSettings) and Wagtail uses its own version wagtail.core.models.Site, and both frameworks expect the Site object they use to be available at request.path..
I worked out this issue by tweaking saleor.core.middelware.site to only modify request.site if we are not visiting a wagtail url (by checking request.path), there are only 2 paths you have to consider, the admin served by 'wagtailadmin_home' (and subpaths) and the pages served by 'wagtail_serve'. Make sure to place the wagtail site middleware before this customized one and thats it, at the admin or when serving pages request.site will have the object wagtail needs, and for the rest it will have the site object saleor needs

**Comment by rosscdh** [comment] 2020-01-11 13:22
@AguD thanks for the tip, works really well
