### ISSUE TITLE
 throw new TypeError('"file" argument must be a non-empty string');

### ISSUE THREAD

**Issue by chenshao0594** [mirumee/saleor#1631] opened 2018-01-16 15:10 UTC
run 'npm run build-assets'  with node 9.4

node ./node_modules/webpack/bin/webpack.js -p

child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:493:38)
    at Object.exports.execFile (child_process.js:209:15)
    at Object.execFile (/Users/shane/projects/saleor/node_modules/pn/_promisify.js:35:27)
    at module.exports (/Users/shane/projects/saleor/node_modules/svg2png/lib/svg2png.js:11:29)
    at Object.nearest (/Users/shane/projects/saleor/node_modules/favicons/helpers-es5.js:302:25)
    at /Users/shane/projects/saleor/node_modules/favicons/es5.js:61:37
    at fn (/Users/shane/projects/saleor/node_modules/async/lib/async.js:746:34)
    at /Users/shane/projects/saleor/node_modules/async/lib/async.js:1213:16
    at /Users/shane/projects/saleor/node_modules/async/lib/async.js:166:37
    at /Users/shane/projects/saleor/node_modules/async/lib/async.js:706:43
    at /Users/shane/projects/saleor/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/Users/shane/projects/saleor/node_modules/async/lib/async.js:710:44)
    at createFavicon (/Users/shane/projects/saleor/node_modules/favicons/es5.js:60:23)
    at /Users/shane/projects/saleor/node_modules/favicons/es5.js:108:24
    at Object.async.forEachOf.async.eachOf (/Users/shane/projects/saleor/node_modules/async/lib/async.js:233:13)
    at createFavicons (/Users/shane/projects/saleor/node_modules/favicons/es5.js:107:19)
    at /Users/shane/projects/saleor/node_modules/favicons/es5.js:118:24
    at /Users/shane/projects/saleor/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/Users/shane/projects/saleor/node_modules/async/lib/async.js:233:13)
    at _parallel (/Users/shane/projects/saleor/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/shane/projects/saleor/node_modules/async/lib/async.js:731:9)
    at createPlatform (/Users/shane/projects/saleor/node_modules/favicons/es5.js:117:19)
    at /Users/shane/projects/saleor/node_modules/favicons/es5.js:135:21
    at Object.async.forEachOf.async.eachOf (/Users/shane/projects/saleor/node_modules/async/lib/async.js:233:13)
    at createOffline (/Users/shane/projects/saleor/node_modules/favicons/es5.js:131:19)
    at create (/Users/shane/projects/saleor/node_modules/favicons/es5.js:178:90)
    at /Users/shane/projects/saleor/node_modules/favicons/es5.js:184:20
    at fn (/Users/shane/projects/saleor/node_modules/async/lib/async.js:746:34)
    at /Users/shane/projects/saleor/node_modules/async/lib/async.js:1213:16

**Comment by rafalp** [comment] 2018-01-16 15:26
Duplicate of #1332

**Closed by rafalp** 2018-01-16 15:26 UTC
