### ISSUE TITLE
When trying to edit the Order model I get the following error: TypeError: '<' not supported between instances of 'ManyToManyField' and 'TaxedMoneyField'

### ISSUE THREAD

**Issue by pchtsp** [mirumee/saleor#4708] opened 2019-09-01 23:40 UTC
I'm well aware that this is most likely my fault for just editing a project by myself without understanding everything that's happening. But it still weird enough to share, I think.

### What I'm trying to achieve

I'm trying to edit the `Order` model in order to incorporate new Date fields for arrival and departure. I've done this already with the `Checkout` model without any issues.

### Steps to reproduce the problem
1. add the following two lines to the `Order` model (`saleor/order/models.py`).
```
arrival = models.DateField(blank=True, null=True)
departure = models.DateField(blank=True, null=True)
```
2. Run `python manage.py makemigrations`

3. Get the following error message: 
`TypeError: '<' not supported between instances of 'ManyToManyField' and 'TaxedMoneyField'`

Which has nothing to do with any of the new fields. So I'm wondering if it just worked by chance because the sorting function that fails found everyhting was sorted and once you unsort the list it gives the error it should always have shown. Or, as I said, there is some assumption I'm not taking into account when happily editing this important model.

### What I expected to happen
when running makemigrations I should expect to see the list of changes in the model and the migrations file created.
…

### Screenshots

I found the following solved issue which I suspect has something todo https://github.com/mirumee/django-prices/issues/61 but since it's solved, I'm not really sure.

**System information**
Operating system: Windows 10
Browser: Google Chrome

Thanks for your help!

**Comment by korycins** [comment] 2019-09-02 06:24
Hi,
If you are using `django-prices` in `version` < 2.0, I know the solution.
The problem is the old version of `django-prices`. There is a bug which generates such strange behavior in Saleor. I recommend you to pull the newest master. We've updated it to the newest version of django-prices. This should solve your problems.

**Comment by maarcingebala** [comment] 2019-09-02 08:01
It was a known issue but as Maciek says it was fixed in the latest version of `django-prices`.

**Closed by maarcingebala** 2019-09-02 08:01 UTC
Labels: support
