### ISSUE TITLE
Stock matching query does not exist.

### ISSUE THREAD

**Issue by Azza-aa** [mirumee/saleor#5183] opened 2020-01-21 15:57 UTC
### What I'm trying to achieve
To save a new product with a user defined product type

### Steps to reproduce the problem
1. Create new product type
2. Try to add a new product selecting my saved product type 

### What I expected to happen
Product should be saved successfully

### Screenshots
![Screenshot_2020-01-21 Create Product Saleor e-commerce](https://user-images.githubusercontent.com/60145108/72820237-4a16bb80-3c77-11ea-97af-8911fa0681a9.png)

**System information**
Operating system: Ubuntu 18.04
Python: 3.6

**Comment by JesusPuga** [comment] 2020-01-21 21:11
I have the same issue. Did you find any solution?

**Comment by JesusPuga** [comment] 2020-01-21 21:24
...
Duplicate of #5180

**Comment by Azza-aa** [comment] 2020-01-22 08:25
> I have the same issue. Did you find any solution?

Not yet

**Comment by maarcingebala** [comment] 2020-01-22 08:52
Closing in favor of #5180.

**Closed by maarcingebala** 2020-01-22 08:52 UTC
