### ISSUE TITLE
Product details doesn't show price/variant/add to cart

### ISSUE THREAD

**Issue by diramazioni** [mirumee/saleor#3274] opened 2018-11-11 23:30 UTC
### What I'm trying to achieve
Product details doesn't show price/variant/add to cart

### Steps to reproduce the problem
I've followed the docs install instructions 

### Screenshots
![image](https://user-images.githubusercontent.com/682046/48319720-9432f480-e611-11e8-9561-38ef9a09a53c.png)

**System information**
Operating system: ubuntu 18.04
Browser: both firefox & chromium

**Comment by diramazioni** [comment] 2018-11-11 23:42
`npm run build-assets --development`
made it work

**Comment by suraj1986** [comment] 2018-11-13 17:43
I am getting the same error and doing the npm run build-assets --development is not working .

**Comment by dinhnghia** [comment] 2018-11-18 06:29
I have the same problem, have you fixed it yet?

**Comment by suraj1986** [comment] 2018-11-18 08:08
No it's not yet solved

**Comment by diramazioni** [comment] 2018-11-18 12:30
have you tried to run
`npm start`
Either this or the other command solved the issue for me

**Comment by suraj1986** [comment] 2018-11-20 05:03
Doing the above steps also not fixed the issue .Please see the error in console [.[](url)](url
<img width="1251" alt="screen shot 2018-11-20 at 10 29 23 am" src="https://user-images.githubusercontent.com/4092926/48752505-a109b500-ecaf-11e8-8f1b-5789d784df76.png">
)

**Comment by suraj1986** [comment] 2018-11-20 05:30
also ,Doing repeatedly .npm -i 
Getting these warning as well.
 npm i
npm WARN babel-loader@7.1.4 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
npm WARN awesome-typescript-loader@5.2.0 requires a peer of typescript@^2.7 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.2 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.

**Comment by suraj1986** [comment] 2018-11-25 18:34
@maarcingebala any  help or suggestion ?

**Comment by suraj1986** [comment] 2018-11-28 18:55
@patrys Its chrome .I just clone and followed the installation instruction .Only the console i am getting error .Is the babel-loader installation is having some issues ?

**Comment by sw80386** [comment] 2018-12-01 03:53
I've the same problem. Only way to fix it so that the product detail page can load the variant options is to add a variant with Options ="---" to the variant.  Then it will display all the variant options in the product detail page. I think it is a bug.

**Comment by maarcingebala** [comment] 2018-12-11 16:57
Does this issue still occur?

**Comment by sw80386** [comment] 2018-12-11 16:58
Yes it does .  I think it is a bug.

On Dec 11, 2018, at 11:57 AM, Marcin Gębala <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this issue still occur?

**Comment by maarcingebala** [comment] 2018-12-11 16:59
Can you check again with latest `master`? Also I'd recommend removing `node_modules`, reinstalling all frontend dependencies and rebuilding static assets. We've updated a bunch of dependencies recently. I'm not able to reproduce it on my machine.

**Comment by sw80386** [comment] 2018-12-11 18:42
Hi Marcin

thank you for your help.
I've a question regarding the images for Variant.
Is it possible for the product page to show the Variant Picture after it is selected instead of rotating images randomly?
How about more than one Variant selected per product?
ie)   A same style of shirt can have different size, different color and different pictures on the shirt.
Can this be done?
If no, do you mind to point me to which file I can modify to make this functions?

thanks
Sunny
________________________________

**Comment by sw80386** [comment] 2018-12-11 19:00
Hi Marcin

Also after I enabled Braintree using sandbox for testing.  I always get this error “unable to process transaction. Please try again in a moment _all__” as shown in attached picture.
This is a clean install I am working on and the clean install fixed the variant selection in the product page.  However, I am still getting the same error in Braintree payment checkout.

Any fix for this?

[image1.jpeg]

Thanks again
Sunny

On Dec 11, 2018, at 12:00 PM, Marcin Gębala <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you check again with latest master? Also I'd recommend removing node_modules, reinstalling all frontend dependencies and rebuilding static assets. We've updated a bunch of dependencies recently. I'm not able to reproduce it on my machine.

**Comment by NyanKiyoshi** [comment] 2019-09-27 13:07
Looks like it is solved. Closing for now unless it occurs again.

**Closed by NyanKiyoshi** 2019-09-27 13:07 UTC
Labels: bug
