### ISSUE TITLE
Storefront: core and demo versions

### ISSUE THREAD

**Issue by weronka** [mirumee/saleor#610] opened 2016-11-07 21:52 UTC
There is an idea to have two templates for Saleor storefront:
- **core**: with a primary functionality, based only on front end framework, without custom JS and any fancy features. It'll be easy to modify and customize in future by developers
- **demo**: will look like a fully functional and nice looking online shop with good UX and UI. This option will present Saleor functionality in more attractive way especially for non-technical persons (designers, managers etc.) 

Now we are thinking about new frond end framework for storefront. There are some options:
- **Foundation**
  +maybe a better grid system
  -JSX problems
  -a lots of microproblems
- **Bootstrap 4**
  +very good community
  +stable
  +a lot of options for customizing forms
  -still alpha version
- **SemanticUI**
  +minimalist design by default
  +behavior features (in ex. animation)
  +/-officila LESS support
  -require adding custom JS almost for every feature
  -heavy package

**Comment by patrys** [comment] 2016-11-07 22:52
I'd like to learn more about the JS problems of Foundation. I've used it with webpack but @mociepka keeps saying that it does not work. Can we get a reproducible way to see what is wrong with it?

**Comment by mociepka** [comment] 2016-11-08 07:51
It does work but it is not in CommonJS you need to use custom loaders for it:

```js
{test: /(foundation\.core)/, loader: 'exports?Foundation,foundation=jQuery.fn.foundation'}
```

If you are using js components in default setup it works but if you try to handle components manually it start to be tricky. They are not modules so simple `require` won't work. You need start to do hackishy code, they are not designed to be extended etc.

As @weronka wrote above we had a lot microproblems with Foundation 6. We were using newest version and some of them was fixed in new releases.

I had a lot of less problems with Bootstrap 3 than Foundation 6 but it is my subjective opinion.

______

We are planing do the demo with some reach js features with CommonJS and it will be nice to have common approach in our frontend lib as well. With that assumption in mind [Bootstrap 4 looks very promising](https://github.com/twbs/bootstrap/tree/v4-dev/js/src).

Another plus are [Bootstrap 4 themes](https://themes.getbootstrap.com/). If we do it right users will be able to use it with Saleor themes as well.

So I would like to use Bootstrap 4 for demo. And if we will have some time move default Saleor theme to it as well.

**Comment by weronka** [comment] 2016-11-08 08:59
I agree with @mociepka. Bootstrap is more stable and popular (will be easy to modificate template by users in future) than Foundation.  Also we had a lots of small problems with JS and changing default styles using Foundation in more advanced project.

**Comment by car3oon** [comment] 2016-11-08 09:14
👍 for @mociepka and **Bootstrap 4**
Besides all the benefits for both storefront versions no one mentioned that we be able to use bootstrap on store dashboard aswell, even with already made [dashboard theme](http://themes.getbootstrap.com/products/dashboard). Major cons against **SemanticUI** are for sure LESS support and heavy package as @weronka mentioned. With **Foundation** we were facing some issues with overwriting default styles and scrpits.

**Comment by artursmet** [comment] 2016-11-15 10:03
@car3oon We can't use already made dashboard theme (a commercial one) because authors won't let us to open source it.

**Comment by weronka** [comment] 2016-11-15 14:36
Demo UX templates:
https://www.figma.com/file/cjGxsI8wyWHbjtLNJzRZB3mI/Saleor-Demo

**Closed** 2016-12-16 16:51 UTC
