### ISSUE TITLE
Text "Description" in Dashboard 2.0 Not Save After clicking "save" button

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4461] opened 2019-07-15 10:01 UTC
![DESCRIPTION](https://user-images.githubusercontent.com/40449637/61208693-3287d480-a722-11e9-80ee-db85c10bce38.PNG)

**Comment by dominik-zeglen** [comment] 2019-07-15 10:23
Can you provide more details?
Next time please use issue template.

**Comment by NyanKiyoshi** [comment] 2019-07-15 13:11
Where is it not saving? Into the database or into the storefront 1.0?

**Comment by zatin009** [comment] 2019-07-15 15:20
@dominik-zeglen  Yes I will use issue template next time, Thank for reminding.

**Comment by zatin009** [comment] 2019-07-15 15:21
@NyanKiyoshi I have checked that it is not saving both in the database neither in the storefront 1.0

**Comment by NyanKiyoshi** [comment] 2019-07-16 11:27
Can you try on the latest master? I am unable to reproduce.

**Comment by zatin009** [comment] 2019-07-17 13:48
I have tried on the latest master. For the database it is not stored.
Could you please check input the data & check with your database again ?
MY DB : PostgreSQL 9.5

**Comment by maarcingebala** [comment] 2019-08-12 08:09
Closing as we're not able to reproduce.

**Closed by maarcingebala** 2019-08-12 08:09 UTC
Labels: dashboard 2.0, support

**Comment by firvida** [comment] 2021-07-31 20:18
I have this exact same issue, Steps to reproduce

`
cd saleor-platform

docker-compose run --rm api python3 manage.py migrate
docker-compose run --rm api python3 manage.py collectstatic --noinput
docker-compose run --rm api python3 manage.py populatedb
docker-compose run --rm api python3 manage.py createsuperuser

docker-compose up -d
`

Then enter in the admin at http://127.0.0.1:9000 find "Carrot Juice" product in catalog and change the description. Save it.
Now you can run. 

`
docker-compose exec db psql -U saleor
select description from product_product where name ilike 'Carrot Juice';
`
IMHO here you should get the text that you entered previously as the description, but instead what I get is:

"Improve your eyesight the natural way with 100% pure, squeezed carrot juice. The sweet, orange nectar of Mother Earth."

which is the default text for that field in the populate db script. Can someone give me a hint on how to get over this error???
