### ISSUE TITLE
No error message when product save fails

### ISSUE THREAD

**Issue by MChiciak** [mirumee/saleor#2265] opened 2018-06-08 03:01 UTC
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
I'd like to see a client side error message when saving a product fails
...

### Steps to reproduce the problem

1.  Introduce an error on the server side on the product save form
2.  Save a product
3.  The page just returns to the original form without any indication anything happened.

### What I expected to happen
I expect an error message to display
...

### What happened instead/how it failed
No error message displayed
...

(Please include a stack trace if this problem results in a crash.)

**Comment by NyanKiyoshi** [comment] 2018-06-08 06:33
Hi!

Could tell us more details about how to reproduce it? 

What kind of error are you talking about? Database issue for example? It should raise a HTTP 500 error as it is not an async request.

**Comment by MChiciak** [comment] 2018-06-09 02:51
Sorry for leaving out more details.

When saving a product that does not have variants (the variant gets automatically created on save), I had some custom logic which would cause the variant to NOT create. 

It is this code found in https://github.com/mirumee/saleor/blob/master/saleor/dashboard/product/views.py

In my case, variant had errors, so no message gets set.  You simply need to put an else statement and set a failure message.

if product_form.is_valid() and not variant_errors:
        product = product_form.save()
        if create_variant:
            variant.product = product
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-details', pk=product.pk)
    ctx = {
        'product_form': product_form, 'variant_form': variant_form,
        'product': product}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)

**Comment by NyanKiyoshi** [comment] 2018-06-09 15:27
I still can't reproduce it.

Here is the main attempt:

1. Go create a product with variant disabled;
2. Fill all valid fields for a product;
3. Don't fill SKU field since it's part of the variant form;
4. Error is being shown.

**Comment by Pacu2** [comment] 2018-06-11 10:01
Can't reproduce it either, is there a possibility that this bug was introduced by the custom logic you've added @MChiciak? Can you reproduce it on the pure saleor?

**Comment by Pacu2** [comment] 2018-07-17 06:48
Closing for now, please reopen if this issue reappears on latest master.

**Closed by Pacu2** 2018-07-17 06:48 UTC
