### ISSUE TITLE
Schema.org for emails

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1371] opened 2017-11-27 14:18 UTC
Google provides rich snippets that may be used in emails:
https://developers.google.com/gmail/markup/overview

Potential usage:
1. [Order confirmation email](https://developers.google.com/gmail/markup/reference/order)
2. [Invoice sent to user](https://developers.google.com/gmail/markup/reference/invoice)
3. [Confirm/reset password action](https://developers.google.com/gmail/markup/reference/one-click-action)

**Acceptance criteria**

- Implemented as JSON-LD
- Generated on the backend, passed to the template
- All changes are documented under `seo` at Read the Docs
- [Need for registering with Google](https://developers.google.com/gmail/markup/registering-with-google) in order to make it work on production servers is mentioned

**Todo**
1. Implement Schema.org for suitable mails in our project
1. Copy email sample and test using [Markup Data Tester](https://www.google.com/webmasters/markup-tester/)
1. Copy email sample and test using [Apps Script](https://developers.google.com/gmail/markup/apps-script-tutorial)

**Helpful resources**
[Testing schema for emails](https://developers.google.com/gmail/markup/testing-your-schema)

**Comment by patrys** [comment] 2017-11-27 14:26
Looks like a duplicate of https://github.com/mirumee/saleor/issues/51

**Closed** 2018-03-14 11:52 UTC
Labels: in progress, seo
